import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import "./globals.css";
import { FlipNav } from "./NavBar";

// Initialize the Inter font
const inter = Inter({
  subsets: ["latin"], 
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <FlipNav />
        {children}
      </body>
    </html>
  );
}


