import type { Metadata } from "next";
import { Goudy_Bookletter_1911 } from "next/font/google"; 
import "./globals.css";
import { FlipNav } from "./NavBar";

// Initialize the GoudyBookletter1911 font
const goudyBookletter1911 = Goudy_Bookletter_1911({
  subsets: ["latin"],
  weight: "400",  // You can specify other weights if needed
});

export const metadata: Metadata = {
  title: "Brock Whitson Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={goudyBookletter1911.className}>
        <FlipNav />
        {children}
      </body>
    </html>
  );
}
